export const weatherImages = {
  "clear sky": "/Img/clearsky.jpg",
  "few clouds": "/Img/fewclouds.jpg",
  "scattered clouds": "/Img/scatteredclouds.jpg",
  "broken clouds": "/Img/brokenclouds.jpg",
  "overcast clouds": "/Img/overcastclouds.jpg",
  "light rain": "/Img/rain.jpg",
  "moderate rain": "/Img/rain1.jpeg",
  "heavy rain": "/Img/rain2.jpg",
  "light snow": "/Img/lightsnow.jpg",
  "moderate snow": "/Img/moderatesnow.jpg",
  "heavy snow": "/Img/heavysnow.jpg",
  "thunderstorm": "/Img/lightning1.jpeg",
  "mist": "/Img/fog.jpg",
  "fog": "/Img/fog.jpg",
  "smoke": "/Img/smoke.jpg",
  "haze": "/Img/haze.jpg",
  "dust": "/Img/dust.png",
  "sand": "/Img/sand.jpg",
  "ash": "/Img/ash.jpg",
  "tornado": "/Img/tornado.jpeg",
  "squalls": "/Img/squalls.png",
  "windy": "/Img/windy.jpg",
  "night": "/Img/night.jpg",
  "sunny":"/Img/sunny 2.jpg",
};

export const weatherIcons = {
  "sunny": "/icons/sunny.svg",
  "clear sky": "/icons/sunny.svg",
  "few clouds": "/icons/clouds.svg",
  "scattered clouds": "/icons/clouds.svg",
  "broken clouds": "/icons/clouds.svg",
  "overcast clouds": "/icons/clouds.svg",
  "light rain": "/icons/rain.svg",
  "moderate rain": "/icons/rain.svg",
  "heavy rain": "/icons/rain.svg",
  "light snow": "/icons/snow.svg",
  "moderate snow": "/icons/snow.svg",
  "heavy snow": "/icons/snow.svg",
  thunderstorm: "/icons/lightning.svg",
  // "mist ": "/Img/fog.jpg",
  // "fog ": "/Img/fog.jpg",
  tornado: "/icons/windy.svg",
  squalls: "/icons/windy.svg",
  windy: "/icons/windy.svg",
  night: "/icons/night.svg",
};
